title: "Learn with Vishal"
description: "Daily learnings on data, tech, and personal growth"
avatar: "/images/avatar.png"  # Upload your own image if you like
author:
  name: "Vishal Boddu"
  bio: "Data engineer, passionate learner & open-source explorer"
