title: Vishal’s Daily Data Dive
description: Insights on data, tech experiments, and growth hacks
name: Vishal Boddu
email: bodduvishal95@gmail.com
avatar: https://avatars.githubusercontent.com/your-github-username
github_username: vishalboddu02
